language: python

services:
  - docker

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS


install:
  - docker build -t $IMAGE_NAME -f .docker/Dockerfile .

after_install:
  - docker tag $IMAGE_NAME $DOCKER_USER/$IMAGE_NAME:$CIRCLE_TAG
  - docker tag $IMAGE_NAME $DOCKER_USER/$IMAGE_NAME:latest
  - docker push $DOCKER_USER/$IMAGE_NAME:$CIRCLE_TAG
  - docker push $DOCKER_USER/$IMAGE_NAME:latest
